# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# The IP address for the server.
# Also stored in vagrant_env_config.sh
private_ip = "192.168.33.20"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos72-x64"
  config.vm.box_url = "https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box"


  # Increase the amount of RAM
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  
  # Share an additional folder to the guest VM. This directory contains
  # scripts that are useful for multiple Vagrant configurations.
  config.vm.synced_folder "../vagrant_shared", "/vagrant_shared"
  config.vm.synced_folder "../reciprocal-borrowing", "/apps/borrow/reciprocal-borrowing"
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: private_ip
    
  # Install and configure necessary components
  config.vm.provision "shell", path: "vm-setup.sh"
end
