# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# The IP address for the server.
# Also stored in vagrant_env_config.sh
private_ip = "192.168.33.20"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # CentOS 7.0, RVM 1.26.11, Ruby 2.2.4
  config.vm.box = 'peichman-umd/ruby'

  config.vm.hostname = 'borrowlocal'

  # Increase the amount of RAM
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.synced_folder "../reciprocal-borrowing", "/apps/borrow/reciprocal-borrowing"
  config.vm.synced_folder 'dist', "/apps/dist"
  config.vm.synced_folder '../borrow-env', '/apps/git/borrow-env'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: private_ip

  # system packages
  config.vm.provision 'puppet', manifest_file: 'borrow.pp'

  # Open HTTP and HTTPS ports
  config.vm.provision "shell", path: "scripts/openports.sh", args: [80, 443]
  # Download, compile, and install Shibboleth
  # checks in /apps/dist for a cached shibboleth-bin.tar.gz first
  config.vm.provision "shell", path: "scripts/shibboleth.sh"
  # runtime environment
  config.vm.provision 'shell', path: 'scripts/env.sh'
  # Apache runtime (setuid script, etc.)
  config.vm.provision "shell", path: "scripts/apache.sh"
  # self-signed HTTPS cert
  config.vm.provision "shell", path: "scripts/https-cert.sh"

  # Shibboleth certs
  config.vm.provision "file", source: 'files/shibboleth/sp-cert.pem',
    destination: '/apps/borrow/certs/cert.pem'
  config.vm.provision "file", source: 'files/shibboleth/sp-key.pem',
    destination: '/apps/borrow/certs/key.pem'

  # install Passenger
  config.vm.provision "shell", path: "scripts/passenger_phusion_setup.sh"
  # Installs bundler globally (TODO: move upstream)
  config.vm.provision "shell", path: "scripts/rvm_setup.sh", privileged: false
  # Bundle install rails app
  config.vm.provision "shell", path: "scripts/rails_app_setup.sh", privileged: false

  # server-specific settings
  config.vm.provision 'file', source: 'files/env', destination: '/apps/borrow/config/env'
  config.vm.provision 'shell', inline: 'cd /apps/borrow/shibboleth && ./control configure', privileged: false
  # start the application
  config.vm.provision 'shell', inline: 'cd /apps/borrow && ./control start', privileged: false
end
